#
# !!! redcarpet should be changed to kramdown since May.1st 2016
# !!! or it would not work

# Dependencies
# markdown: CommonMarkGhPages

markdown:           kramdown
kramdown:
   input: GFM
   hard_wrap: false


#markdown:           redcarpet
#redcarpet:
# extensions:       ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# default highlighter would be changed to rouge in 2016
highlighter:        rouge

#github settings
baseurl:
assetsurl:          /assets
jsurl:              /assets/js
cssurl:             /assets/css
imgurl:             /assets/img
dnldurl:            /assets/download
gem:

# Permalinks
permalink:          pretty

#Server
# host:               127.0.0.1
# port:               4000
# baseurl:            /
# url:                http://localhost:4000
# encoding:           UTF-8

# the excluded directoies
exclude:            []

# site information
info:
  site_name:        Vpon-SDK

meta:
  description:      "Here presents the latest Vpon SDK documentation."
  keywords:         ["Vpon", 'SDK', 'wiki', 'documentation', 'document', 'banner', 'interstitial', 'ad', 'mobile', 'integration']
  author:           "Vpon MI"

# multiple language
lang:          ["en", "zh-tw", "zh-cn", "jp"]

# left navigation
left_nav:
  en:
    title:          "Vpon SDK"
    path:           /
    # items:
    #   - path:       /page1
    #     title:      "Another page"
    #   - path:       /page2
    #     title:      "Yet another page"
  zh-tw:
    title:          "Vpon SDK"
    path:           /zh-tw

  zh-cn:
    title:          "Vpon SDK"
    path:           /zh-cn

  jp:
    title:          "Vpon SDK"
    path:           /jp


# new right navigation
right_nav_new:
  - title: Android
    cls: right-android
    url1: /android/
    url2: /zh-tw/android/
    url3: /zh-cn/android/
    url4: /jp/android/
  - title: iOS
    cls: right-ios
    url1: /ios/
    url2: /zh-tw/ios/
    url3: /zh-cn/ios/
    url4: /jp/ios/
  - title: Web
    cls: right-web
    url1: /web/
    url2: /zh-tw/web/
    url3: /zh-cn/web/
    url4: /jp/web/


# languages
languages:
  - title: English
  - title: 繁體中文
  - title: 简体中文
  - title: 日本語



# analytics account information, remember to change this.
analytics:
  google:
    account:         UA-66722167-2

#version
a_version:          5.4.4
i_version:          5.4.4
